# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

address:
  IP: 34.121.112.72

image:
        repository: ajitsingh25/mediawiki:v2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

db:
  hostname: mysql-svc
  dbname: mydb
  dbuser: root
  dbpassword: password
    
service:
  type: ClusterIP
  port: 80

resources: 
  limits:
    cpu: 500m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
